version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_1
    environment:
      MYSQL_ROOT_PASSWORD: koreait123414
      MYSQL_DATABASE: tails_route
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/var/lib/mysql:/var/lib/mysql
    networks:
      - tailsroute_network
    restart: unless-stopped

  # 다른 서비스들 (예: Spring Boot 애플리케이션)을 여기에 추가할 수 있습니다.

networks:
  tailsroute_network:
    driver: bridge